import {StyleSheet} from 'react-native';
import {colors, metrics, size} from '../../theme';

const Styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.primary},
  viewHeader: {
    zIndex: 1,
    flex: 1.1,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: '#ffa502',
  },
  viewTitleShop: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'row',
    padding: 10,
  },
  viewMenu: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    flexDirection: 'row',
  },
  buttonItem: {
    marginTop: '15%',
    height: '50%',
    width: '40%',
    marginRight: '5%',
    borderRadius: 10,
    borderColor: colors.yellowMain,
    borderWidth: 1,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonPesan: {
    marginTop: '15%',
    height: '50%',
    width: '40%',
    marginLeft: '5%',
    borderRadius: 10,
    borderColor: colors.yellowMain,
    borderWidth: 1,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconButton: {fontSize: 40, color: colors.yellowMain},
  subHeader: {flex: 1, flexDirection: 'row'},
  subCardHeaderA: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 20,
  },
  subCardHeaderB: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: 20,
  },
  subCardHeaderC: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 20,
  },
  subCardHeaderD: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomRightRadius: 20,
  },
  cardIncome: {
    zIndex: 2,
    flex: 2.5,
    top: '20%',
    marginHorizontal: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    position: 'relative',
    backgroundColor: colors.primary,
  },
  fontTitle: {
    marginBottom: 5,
    marginHorizontal: 10,
    fontSize: size.font12,
    fontFamily: 'NexaXBold',
    color: colors.fontMain,
  },
  fontTitle2: {
    marginBottom: 5,
    marginHorizontal: 10,
    fontSize: size.font12,
    fontFamily: 'NexaXBold',
    color: colors.yellowMain,
  },
  fontUser: {
    flex: 1,
    marginTop: 5,
    marginHorizontal: 10,
    fontSize: size.font18,
    fontFamily: 'NexaXBold',
    color: colors.primary,
  },
  fontTime: {
    flex: 1,
    marginTop: 5,
    marginHorizontal: 10,
    fontSize: size.font18,
    fontFamily: 'NexaXBold',
    textAlign: 'right',
    color: colors.primary,
  },
  fontCount: {
    marginBottom: 5,
    fontSize: size.font20,
    fontFamily: 'NexaXBold',
    color: colors.fontMain,
  },
  iconShope: {fontSize: 30, color: colors.primary},
  viewFooter: {flex: 1, paddingTop: 10, backgroundColor: colors.primary},
});

export default Styles;
